/*
 * This source file was generated by the Gradle 'init' task
 */
package org.bruschi;

public class App {    

    public static void main(String[] args) {
        
        System.out.println("dgwgweh");
        
    }
    
}
