/*
 * This source file was generated by the Gradle 'init' task
 */
package org.main;

import javax.swing.JFrame;

import org.CaixaRapido.CaixaRapido;

public class App {

    public static void main(String[] args) {

        var caixaRapido = new CaixaRapido();

        // caixaRapido.setUndecorated(true);

        //caixaRapido.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

}
