/*
 * This source file was generated by the Gradle 'init' task
 */
package org.main;

import CaixaRapido;
import javax.swing.JFrame;

public class App {

    public static void main(String[] args) {

        var caixaRapido = new CaixaRapido();

        // caixaRapido.setUndecorated(true);

        caixaRapido.setExtendedState(JFrame.MAXIMIZED_BOTH);

        caixaRapido.setVisible(true);

        // var main = new JFrame();
        //
        // var mainPanel = new JPanel();
        //
        // main.add(mainPanel);
        //
        // main.setSize(300, 300);
        //
        // main.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //
        // main.setVisible(true);
        //
        // var a = new JOptionPane("asasg");
        // main.add(a);

    }

}
